# Generated by Django 4.0.4 on 2022-07-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventFrom',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventTo',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventType',
            field=models.TextField(choices=[('Full-time', 'Fulltime'), ('Part-time', 'Parttime'), ('Apprenticeship', 'Apprenticeship'), ('Shadowing', 'Shadowing')], default='Full-time'),
        ),
    ]
