# Generated by Django 4.0.4 on 2022-07-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_eventfrom_alter_events_eventto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventFrom',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventTo',
            field=models.DateField(null=True),
        ),
    ]
