# Generated by Django 4.0.4 on 2022-07-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_eventfrom_alter_events_eventto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventTo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
