# Generated by Django 4.0.4 on 2022-07-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalinfo',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('jobTitle', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('gitProfileLink', models.CharField(blank=True, max_length=500, null=True)),
                ('gitApiLink', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedInLink', models.CharField(blank=True, max_length=500, null=True)),
                ('instagramApiLink', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
