# Generated by Django 4.0.4 on 2022-07-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='instagramApiLink',
        ),
    ]
