# Generated by Django 4.0.4 on 2022-07-17 06:23

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0002_remove_personalinfo_instagramapilink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='description',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
