# Generated by Django 4.0.4 on 2022-07-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0003_alter_personalinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='telephone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
